/**
   * Prewarms MAMA expression PNGs into the browser image cache.
   * Generated by scripts/build-mama-exp-regex.ts.
 */
(function () {
  'use strict';

  const CURRENT_ROOT = typeof window !== 'undefined' ? window : globalThis;
  const DEFAULT_APP_BASE_URL = 'https://hasheeper.github.io/project-mama-ena';
  const ASSET_REFS = {"base":["nephilim","nightwear","nude","outfit_winter","school_uniform","seraphim","streetwear_full","streetwear_inner","underwear"],"face":["face_blush_heavy","face_blush_light","face_default","face_pale","face_shadow"],"eye":["eye_avert","eye_closed_1","eye_closed_2","eye_cry_1","eye_cry_2","eye_cry_3","eye_dark","eye_disgust","eye_dizzy_1","eye_dizzy_2","eye_half_1","eye_half_2","eye_heart","eye_jitome","eye_line","eye_normal","eye_puppy","eye_shock","eye_slit","eye_smile","eye_star","eye_wide","eye_wink_2","eye_xd"],"mouth":["mouth_awawa","mouth_bite_lip","mouth_blank_1","mouth_blank_2","mouth_cat","mouth_down","mouth_drool","mouth_fang_open","mouth_huh","mouth_laugh","mouth_laugh_happy","mouth_neutral","mouth_panic_open","mouth_pout_2","mouth_shock","mouth_smile","mouth_smirk_1","mouth_smirk_2","mouth_tongue_2","mouth_tremble_1"],"brow":["brow_down","brow_normal","brow_question","brow_up","brow_up_max"],"other":["pale_1","pale_2","pale_3","shadow_1","shadow_2","shadow_3","sweat"],"emotion":["Emotion_Amazed","Emotion_Angry","Emotion_Confusion","Emotion_Curiosity","Emotion_Distress","Emotion_Excited","Emotion_Fearful","Emotion_Glee","Emotion_Heart","Emotion_Laughter","Emotion_Line","Emotion_Shocked","Emotion_Sigh","Emotion_Sleepy","Emotion_Sparkle","Emotion_Star","Emotion_Steam","Emotion_Surprise","Emotion_Surprise2","Emotion_Sweat","Emotion_zzz"]};
  const CACHE_KEY = '__MAMA_EXP_IMAGE_CACHE__';

  function readGlobalString(key) {
    const targets = [CURRENT_ROOT];
    try { targets.push(CURRENT_ROOT.parent); } catch (_) {}
    try { targets.push(CURRENT_ROOT.top); } catch (_) {}
    for (const target of targets) {
      try {
        if (typeof target?.[key] === 'string' && target[key].trim()) return target[key].trim();
      } catch (_) {}
    }
    return '';
  }

  function trimTrailingSlash(value) {
    return typeof value === 'string' ? value.trim().replace(/\/+$/, '') : '';
  }

  function resolveAssetBaseUrl() {
    const explicit = readGlobalString('MAMA_ASSET_BASE_URL');
    if (explicit) return trimTrailingSlash(explicit);
    const appBase = trimTrailingSlash(readGlobalString('MAMA_APP_BASE_URL') || DEFAULT_APP_BASE_URL);
    return appBase + '/mama-assets/standing';
  }

  function assetUrl(baseUrl, group, name) {
    const folders = {
      base: 'base',
      face: 'expression/face_fx',
      eye: 'expression/eyes',
      mouth: 'expression/mouth',
      brow: 'expression/brow',
      other: 'expression/other',
      emotion: 'emotion'
    };
    return baseUrl + '/' + folders[group] + '/' + encodeURIComponent(name) + '.png';
  }

  function getAllAssetUrls(baseUrl) {
    return [].concat(
      ASSET_REFS.base.map((name) => assetUrl(baseUrl, 'base', name)),
      ASSET_REFS.face.map((name) => assetUrl(baseUrl, 'face', name)),
      ASSET_REFS.mouth.map((name) => assetUrl(baseUrl, 'mouth', name)),
      ASSET_REFS.eye.map((name) => assetUrl(baseUrl, 'eye', name)),
      ASSET_REFS.brow.map((name) => assetUrl(baseUrl, 'brow', name)),
      ASSET_REFS.other.map((name) => assetUrl(baseUrl, 'other', name)),
      ASSET_REFS.emotion.map((name) => assetUrl(baseUrl, 'emotion', name))
    );
  }

  function getCacheRoot() {
    const candidates = [CURRENT_ROOT];
    try { candidates.push(CURRENT_ROOT.parent); } catch (_) {}
    try { candidates.push(CURRENT_ROOT.top); } catch (_) {}
    for (const target of candidates) {
      try {
        if (target && target.Object) return target;
      } catch (_) {}
    }
    return CURRENT_ROOT;
  }

  function warmImageCache(urls) {
    const root = getCacheRoot();
    let cache;
    try {
      cache = root[CACHE_KEY] || (root[CACHE_KEY] = Object.create(null));
    } catch (_) {
      cache = CURRENT_ROOT[CACHE_KEY] || (CURRENT_ROOT[CACHE_KEY] = Object.create(null));
    }

    urls.forEach((url) => {
      if (!url || cache[url]) return;
      const image = new Image();
      cache[url] = { status: 'loading', image };
      image.decoding = 'async';
      try { image.fetchPriority = 'low'; } catch (_) {}
      image.onload = function () { cache[url].status = 'ready'; };
      image.onerror = function () { cache[url].status = 'error'; };
      image.src = url;
    });
  }

  function warmExpressionAssets() {
    const baseUrl = resolveAssetBaseUrl();
    const urls = getAllAssetUrls(baseUrl);
    warmImageCache(urls.slice(0, 8));
    setTimeout(() => warmImageCache(urls.slice(8)), 300);
    return { baseUrl, count: urls.length };
  }

  try {
    const runtime = CURRENT_ROOT.MAMAMainRuntime || {};
    runtime.warmExpressionAssets = warmExpressionAssets;
    CURRENT_ROOT.MAMAMainRuntime = runtime;
  } catch (_) {}

  const result = warmExpressionAssets();
  try {
    console.info('[MAMA Asset Cache] warming expression PNG cache:', result);
  } catch (_) {}
})();
